select*from member;
select*from IMAGE;
commit;
CREATE SEQUENCE IMG_SEQ
    START WITH 1000
    INCREMENT BY 1 ;
CREATE TABLE IMAGE(
    IMG_SEQ DECIMAL PRIMARY KEY,
    IMAGE_NAME VARCHAR2(20),
    EXTENSION VARCHAR2(20),
    USERID VARCHAR2(20),
    CONSTRAINT FK_IMAGE_MEMBER
    FOREIGN KEY (USERID)
    REFERENCES MEMBER (USERID) 
);
DROP TABLE IMAGE;


INSERT INTO IMAGE(IMG_SEQ,IMAGE_NAME,EXTENSION,USERID)
VALUES('IMG_SEQ.NEXTVAL','','','');

SELECT USERID,   NAME ,  SSN,  PASSWORD,  GENDER,  AGE,  ROLL, TEAMID
FROM MEMBER 
 WHERE USERID LIKE 'rlawldms'
  AND PASSWORD LIKE '0828' ;
  
