drop table member;
select * from member; 
ALTER TABLE MEMBER RENAME COLUMN AGE TO SSN;
ALTER TABLE MEMBER MODIFY(SSN VARCHAR2(5));
alter table member drop column SSN;
ALTER TABLE MEMBER ADD(PASSWORD VARCHAR2(20));
INSERT INTO MEMBER (PASSWORD) VALUES ('1');
UPDATE MEMBER SET PASSWORD='1';


alter table teamw rename to member;
ALTER TABLE MEMBER RENAME COLUMN MEM_SSN TO SSN;