CREATE SEQUENCE SUB_SEQ START WITH 5;
CREATE SEQUENCE RECORD_SEQ START WITH 1;
CREATE SEQUENCE EXAM_SEQ START WITH 1;


CREATE TABLE SUBJECT(
    SUB_SEQ DECIMAL PRIMARY KEY,
    SUB_NAME VARCHAR2(20));
  
INSERT INTO SUBJECT
(SUB_SEQ,SUB_NAME) VALUES (SUB_SEQ.NEXTVAL, 'JAVA');
INSERT INTO SUBJECT
(SUB_SEQ,SUB_NAME) VALUES (SUB_SEQ.NEXTVAL, 'SQL');
INSERT INTO SUBJECT 
(SUB_SEQ,SUB_NAME)VALUES (SUB_SEQ.NEXTVAL, 'HTML5');
INSERT INTO SUBJECT
(SUB_SEQ,SUB_NAME) VALUES (SUB_SEQ.NEXTVAL, 'PYTHON');
INSERT INTO SUBJECT
(SUB_SEQ,SUB_NAME) VALUES (SUB_SEQ.NEXTVAL, 'R');
SELECT * FROM SUBJECT;

CREATE TABLE RECORD (
    RECORD_SEQ DECIMAL PRIMARY KEY,
    GRADE VARCHAR2 (20),
    AVG VARCHAR2 (20)
);
SELECT * FROM RECORD;

CREATE TABLE EXAM(
    EXAM_SEQ DECIMAL PRIMARY KEY, 
    SUB_SEQ DECIMAL ,
    RECORD_SEQ DECIMAL,
    MEM_ID VARCHAR2 (20),
    MONTH VARCHAR2 (20),
    SCORE VARCHAR2(20)
);
DROP TABLE EXAM;
ALTER TABLE EXAM ADD CONSTRAINTS SUBJECT_FK_SUB_SEQ
FOREIGN KEY (SUB_SEQ) REFERENCES SUBJECT(SUB_SEQ);
ALTER TABLE EXAM ADD CONSTRAINTS RECORD_FK_RECORD_SEQ
FOREIGN KEY (RECORD_SEQ) REFERENCES RECORD(RECORD_SEQ);
SELECT * FROM EXAM;