SELECT * FROM MEMBER;
UPDATE MEMBER SET PASSWORD ='8';
UPDATE MEMBER SET SSN='930109-1' WHERE MEM_ID LIKE 's4';
SELECT 
    MEM_ID USERID,
    PASSWORD
FROM MEMBER;
UPDATE MEMBER SET PASSWORD = '7'
WHERE MEM_ID LIKE 'MIC'
AND PASSWORD LIKE '';
DELETE FROM MEMBER 
WHERE MEM_ID LIKE 'MICKEY' 
AND PASSWORD LIKE '8';
commit;

SELECT 
    MEM_ID USERID,
    TEAM_ID TEAMID,
    NAME,
    SSN,
    ROLL,
    PASSWORD
FROM MEMBER;

SELECT COUNT(*) AS count FROM MEMBER;

SELECT NAME 
FROM MEMBER
WHERE NAME LIKE 'ÁöÀº';

SELECT MEM_ID USERID,
    TEAM_ID TEAMID,
    NAME,
    SSN,
    ROLL,
    PASSWORD
FROM MEMBER
WHERE MEM_ID LIKE 'h2';