SELECT T.* 	
FROM(SELECT ROWNUM SEQ, M.* 	
FROM MEMBER M 	ORDER BY SEQ DESC)T 
	WHERE T.SEQ BETWEEN 1 AND 5;
	
	
SELECT T.* 	
FROM(SELECT ROWNUM SEQ, M.* 	
FROM MEMBER M 	ORDER BY SEQ DESC)T 
	WHERE T.SEQ BETWEEN 1 AND 5
     ;
     
     
SELECT ROWNUM SEQ, M.* 	
FROM MEMBER M 	
    WHERE TEAMID LIKE 'ateam'
    ORDER BY SEQ DESC;
    
    
SELECT T.* 	
FROM(SELECT ROWNUM SEQ, M.* 	
FROM MEMBER M 	
    WHERE TEAMID LIKE 'ateam'
    ORDER BY SEQ DESC)T 
	WHERE T.SEQ BETWEEN 1 AND 5;